### ISSUE TITLE
[1.1.0] Torches start fires even if config option to do so is disabled

### ISSUE THREAD

**Issue by IdrisQe** [DoubleDoorDevelopment/BurningTorch#12]
Rarely, a burning torch will still set blocks around it on fire, even when the relevant config option is disabled. Version 1.1.0 for 1.12.2. Turning fire tick off seems to be the only way to prevent this.
My house has been damaged twice due to this already. It's really kind of insufferable.

EDIT: I looked at the code, and as you can see, the block-burning logic doesn't check for the config option at all. This would be an incredibly simple fix.

```
    @Override
    public void updateTick(World worldIn, BlockPos pos, IBlockState state, Random rand)
    {
        if (worldIn.getGameRules().getBoolean("doFireTick"))
        {
            int i = rand.nextInt(3);

            if (i > 0)
            {
                BlockPos blockpos = pos;

                for (int j = 0; j < i; ++j)
                {
                    blockpos = blockpos.add(rand.nextInt(3) - 1, 1, rand.nextInt(3) - 1);

                    if (blockpos.getY() >= 0 && blockpos.getY() < worldIn.getHeight() && !worldIn.isBlockLoaded(blockpos))
                    {
                        return;
                    }

                    IBlockState block = worldIn.getBlockState(blockpos);

                    if (block.getBlock().isAir(block, worldIn, blockpos))
                    {
                        if (this.isSurroundingBlockFlammable(worldIn, blockpos))
                        {
                            worldIn.setBlockState(blockpos, Blocks.FIRE.getDefaultState());
                            return;
                        }
                    }
                    else if (block.getMaterial().blocksMovement())
                    {
                        return;
                    }
                }
            }
            else
            {
                for (int k = 0; k < 3; ++k)
                {
                    BlockPos blockpos1 = pos.add(rand.nextInt(3) - 1, 0, rand.nextInt(3) - 1);

                    if (blockpos1.getY() >= 0 && blockpos1.getY() < 256 && !worldIn.isBlockLoaded(blockpos1))
                    {
                        return;
                    }

                    if (worldIn.isAirBlock(blockpos1.up()) && this.getCanBlockBurn(worldIn, blockpos1))
                    {
                        worldIn.setBlockState(blockpos1.up(), Blocks.FIRE.getDefaultState());
                    }
                }
            }
        }
}
```

All that would be needed is to add a check for the config either before alongside the doFireTick check.

**Comment by Claycorp** [comment]
I'll take a look at it quick.

Also as a tidbit of helpful info for if you click on a line number on github it will highlight it and give you some extra options along with a line location URL, Like so: `https://github.com/DoubleDoorDevelopment/BurningTorch/blob/f5b61935908debfb8f3c0fffd35e569b866f8093/src/main/java/net/doubledoordev/burningtorch/blocks/BlockBurningTorch.java#L1076`
It will automatically convert it to a snip like this:
https://github.com/DoubleDoorDevelopment/BurningTorch/blob/f5b61935908debfb8f3c0fffd35e569b866f8093/src/main/java/net/doubledoordev/burningtorch/blocks/BlockBurningTorch.java#L1076

Shift clicking another line after the first will give you a group too.

**Comment by Claycorp** [comment]
Alright I see got messed up.
`torchesStartFireWhenLit` is checked but on the wrong tick method. I used `updateTick` and the check was done on `randomTick` via enabling/disabling random ticks.

My bad, glad you reported it! There will be a new build on CF shortly.
