### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by CapitaineYolo** [DoubleDoorDevelopment/BurningTorch#16]
Hey ^^ With this mod installed on forge 1.18.1 (and nothing else) I receive this crashlog when placing a burning torch: 

The game crashed whilst exception ticking world
Error: java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag net.doubledoordev.burningtorch.blocks.blockentities.BurningLightBlockEntity.save(net.minecraft.nbt.CompoundTag)'
Exit-Code: -1

**Comment by Claycorp** [comment]
This is due to a breaking change in forge 21+ for 1.18.1
A new version will be on CF shortly fixing this.
