### ISSUE TITLE
Option to toggle unlit torch as the default placed torch.

### ISSUE THREAD

**Issue by Claycorp** [DoubleDoorDevelopment/BurningTorch#5]
Tile.

**Comment by darchitectlp** [comment]
Yes, please! I prefer your mod to realistic torches, but I need a way to place unlit torches. Thanks!

**Comment by Claycorp** [comment]
Sorry this hasn't been done sooner, It should take all of 5-10 minutes to do....
I'll see if I can get the stuff in #3 done also. There should be a new version up later today if this issue gets closed.

**Comment by Claycorp** [comment]
Added in f831e3c83d4727b293ac12e9316aa26726210fdf
